[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18" # Ensure you use a compatible Node.js version

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
  force = true
