[build]
  command = "npm run build" # The build command you use
  publish = ".next"         # Directory to publish after build

[[plugins]]
package = "@netlify/plugin-nextjs" # Netlify Next.js plugin
    