import { Inter } from "next/font/google";
import "./globals.css";
import { EmployeeProvider } from "./context/EmployeeContext";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "./components/Header";
import { AuthProvider } from "./context/AuthContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <EmployeeProvider>
          <Header />
          {children}
        </EmployeeProvider>
        </AuthProvider>
      </body>
    </html>

  );
}
